name: Build

on: workflow_dispatch

jobs:
  windows:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.7.2
    steps:
      - uses: actions/checkout@v5
      - run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.7.2.stable ~/.local/share/godot/export_templates/
          mkdir -p build
          godot --headless --import
          godot --headless --export-release "Windows Desktop" build/TheLastContract.exe
      - uses: actions/upload-artifact@v4
        with:
          name: the-last-contract-windows
          path: build
